[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/explore"
  to = "/explore.html"
  status = 200

[[redirects]]
  from = "/explore/issues"
  to = "/connect.html"
  status = 200

[[redirects]]
  from = "/explore/issues/connect"
  to = "/Issues.html"
  status = 200

[[redirects]]
  from = "/pending"
  to = "/Pending.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
